name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run Node steps only if your backend has package.json
      - name: Setup Node
        if: hashFiles('backend/**/package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        if: hashFiles('backend/**/package.json') != ''
        working-directory: backend
        run: npm ci

      - name: Test
        if: hashFiles('backend/**/package.json') != ''
        working-directory: backend
        run: npm test --if-present

      # Add other backend checks here (lint, build, docker, etc.)
